default_platform(:android)

platform :android do
  desc "Runs unit and widget tests"
  lane :test do
    Dir.chdir("../..") do
      sh("flutter test")
    end
  end

  desc "Builds signed Android App Bundle (AAB)"
  lane :build_bundle do
    Dir.chdir("../..") do
      sh("flutter build appbundle --release")
    end
  end

  desc "Deploy a new version to the Google Play Store Closed Testing Track"
  lane :deploy_internal do
    build_bundle
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
